# Generated by Django 5.2.17 on 2026-08-26 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_productionprogram_mold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionHistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_uid', models.CharField(db_index=True, max_length=32, verbose_name='شناسه برنامه')),
                ('plan_date', models.DateField(blank=True, null=True, verbose_name='تاریخ برنامه')),
                ('mold_change_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تعویض قالب')),
                ('unit_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='شماره واحد')),
                ('machine_number', models.CharField(blank=True, max_length=40, verbose_name='شماره دستگاه')),
                ('product_code', models.CharField(blank=True, max_length=80, verbose_name='کد کالا')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='نام محصول')),
                ('mold_name', models.CharField(blank=True, max_length=200, verbose_name='نام قالب')),
                ('material', models.CharField(blank=True, max_length=120, verbose_name='مواد')),
                ('color', models.CharField(blank=True, max_length=80, verbose_name='رنگ')),
                ('sequence', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ترتیب')),
                ('planned_qty', models.IntegerField(blank=True, null=True, verbose_name='مقدار برنامه')),
                ('produced_qty', models.IntegerField(blank=True, null=True, verbose_name='مقدار تولید')),
                ('status', models.CharField(blank=True, max_length=80, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('source_table_name', models.CharField(blank=True, max_length=200, verbose_name='نام جدول مبدأ')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='انتقال\u200cدهنده')),
            ],
            options={
                'verbose_name': 'سابقه تولید',
                'verbose_name_plural': 'سوابق تولید (آرشیو)',
                'ordering': ['program_uid', 'id'],
            },
        ),
    ]
