# Generated by Django 5.2.17 on 2026-08-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_history_and_transfer_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionhistoryrecord',
            name='active_cavities',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد حفره فعال'),
        ),
        migrations.AddField(
            model_name='productionhistoryrecord',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع واقعی'),
        ),
        migrations.AddField(
            model_name='productionhistoryrecord',
            name='last_cavities',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='آخرین وضعیت حفره'),
        ),
        migrations.AddField(
            model_name='productionhistoryrecord',
            name='last_cycle',
            field=models.IntegerField(blank=True, null=True, verbose_name='آخرین سیکل تولید'),
        ),
        migrations.AddField(
            model_name='productionhistoryrecord',
            name='mold_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='شماره قالب'),
        ),
        migrations.AddField(
            model_name='productionhistoryrecord',
            name='plan_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='شماره برنامه'),
        ),
        migrations.AddField(
            model_name='productionhistoryrecord',
            name='plan_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع برنامه'),
        ),
        migrations.AddField(
            model_name='productionhistoryrecord',
            name='planned_cycle',
            field=models.IntegerField(blank=True, null=True, verbose_name='سیکل تولید برنامه'),
        ),
        migrations.AddField(
            model_name='productionhistoryrecord',
            name='planned_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ساعت تولید برنامه'),
        ),
        migrations.AddField(
            model_name='productionhistoryrecord',
            name='scrap_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='ضایعات تولید'),
        ),
        migrations.AddField(
            model_name='productionhistoryrecord',
            name='unique_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='کد یکتا'),
        ),
        migrations.AlterField(
            model_name='productionhistoryrecord',
            name='plan_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ برنامه\u200cریزی'),
        ),
        migrations.AlterField(
            model_name='productionhistoryrecord',
            name='planned_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار تولید برنامه'),
        ),
        migrations.AlterField(
            model_name='productionhistoryrecord',
            name='produced_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار تولید واقعی'),
        ),
        migrations.AlterField(
            model_name='productionhistoryrecord',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام جنس'),
        ),
        migrations.AlterField(
            model_name='productionhistoryrecord',
            name='program_uid',
            field=models.CharField(db_index=True, max_length=32, verbose_name='شناسه تعویض'),
        ),
    ]
