# Generated by Django 5.2.17 on 2026-08-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_history_record_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionhistoryrecord',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان تولید'),
        ),
    ]
