# Generated by Django 5.2.17 on 2026-09-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_history_end_date_and_conflict_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeproduction',
            name='socket_length',
            field=models.CharField(blank=True, choices=[('30cm_1s', '۳۰ سانتی یک\u200cسر سوکت'), ('50cm_1s', 'نیم\u200cمتری یک\u200cسر سوکت'), ('100cm_1s', '۱ متری یک\u200cسر سوکت'), ('200cm_1s', '۲ متری یک\u200cسر سوکت'), ('300cm_1s', '۳ متری یک\u200cسر سوکت'), ('50cm_2s', 'نیم\u200cمتری دوسر سوکت'), ('100cm_2s', '۱ متری دوسر سوکت'), ('200cm_2s', '۲ متری دوسر سوکت'), ('300cm_2s', '۳ متری دوسر سوکت')], max_length=20, verbose_name='اندازه لوله (سوکت)'),
        ),
    ]
