# Generated by Django 5.2.17 on 2026-08-11 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_moldoption'),
        ('planning', '0003_weeklyplanitem_sequence_weeklyplanitem_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplanline',
            name='mold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.moldoption', verbose_name='انتخاب قالب'),
        ),
    ]
