# Generated by Django 5.2.17 on 2026-08-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_weeklyplanline_mold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyplan',
            name='status',
            field=models.CharField(choices=[('draft', 'در انتظار تأیید'), ('approved', 'تأییدشده')], default='draft', max_length=12),
        ),
    ]
