# Generated by Django 5.2.17 on 2026-08-19 06:44

import django_jalali.db.models
from django.db import migrations


def dedupe_plan_dates(apps, schema_editor):
    WeeklyPlan = apps.get_model("planning", "WeeklyPlan")
    seen = {}
    for plan in WeeklyPlan.objects.order_by("id"):
        key = str(plan.date)
        if key not in seen:
            seen[key] = plan.pk
            continue
        # Shift older duplicates backward until free.
        try:
            import jdatetime
            cur = plan.date
            if not hasattr(cur, "togregorian"):
                # Stored as date-like
                pass
            new = plan.date
            for step in range(1, 400):
                try:
                    new = plan.date - jdatetime.timedelta(days=step)
                except Exception:
                    break
                clash = WeeklyPlan.objects.filter(date=new).exclude(pk=plan.pk).exists()
                if not clash and str(new) not in seen:
                    plan.date = new
                    plan.save(update_fields=["date"])
                    seen[str(new)] = plan.pk
                    break
        except Exception:
            # Last resort: skip; AlterField may still fail and need manual fix.
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0006_weeklyplanline_uid"),
    ]

    operations = [
        migrations.RunPython(dedupe_plan_dates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="weeklyplan",
            name="date",
            field=django_jalali.db.models.jDateField(unique=True, verbose_name="تاریخ برنامه‌ریزی"),
        ),
    ]
