# Generated by Django 5.2.17 on 2026-09-02 16:02

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_planning_display_width_label'),
        ('planning', '0009_line_production_type_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='planning_mode',
            field=models.CharField(choices=[('manual', 'دستی'), ('systemic', 'سیستمی')], default='manual', max_length=12, verbose_name='نحوه برنامه\u200cریزی'),
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=40, verbose_name='کد کالا')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='نام کالا')),
                ('period_label', models.CharField(blank=True, max_length=80, verbose_name='دوره پیش\u200cبینی')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='مقدار پیش\u200cبینی')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('source_table_name', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_forecasts', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'پیش\u200cبینی فروش',
                'verbose_name_plural': 'پیش\u200cبینی فروش',
                'ordering': ['product_code', 'period_label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='شماره سفارش')),
                ('product_code', models.CharField(db_index=True, max_length=40, verbose_name='کد کالا')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='نام کالا')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='مقدار سفارش')),
                ('delivery_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('priority', models.PositiveIntegerField(default=100, help_text='عدد کمتر = اولویت بالاتر', verbose_name='اولویت')),
                ('is_backlog', models.BooleanField(default=False, verbose_name='سفارش معوق')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='مشتری')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('source_table_name', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['priority', 'delivery_date', 'id'],
                'indexes': [models.Index(fields=['order_ref', 'product_code'], name='planning_cu_order_r_2c0dc1_idx')],
            },
        ),
    ]
