# Generated by Django 5.2.17 on 2026-09-02 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_inventory_orders_and_systemic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningProcessDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='کد فرآیند')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('entry_step_number', models.PositiveIntegerField(default=1, verbose_name='شماره مرحله شروع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تعریف فرآیند برنامه\u200cریزی',
                'verbose_name_plural': 'تعاریف فرآیند برنامه\u200cریزی',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PlanningProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='شماره مرحله')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مرحله')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('kind', models.CharField(choices=[('action', 'اقدام'), ('decision', 'سوال بله/خیر'), ('terminal', 'پایان')], default='action', max_length=12, verbose_name='نوع')),
                ('question', models.CharField(blank=True, max_length=500, verbose_name='متن سوال (برای بله/خیر)')),
                ('yes_next_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='در صورت بله → مرحله')),
                ('no_next_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='در صورت خیر → مرحله')),
                ('next_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='مرحله بعدی (برای اقدام)')),
                ('data_binding', models.CharField(default='none', help_text='کلید اتصال به موجودی، BOM، سفارشات، قالب و …', max_length=40, verbose_name='اتصال به داده سیستم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='planning.planningprocessdefinition', verbose_name='فرآیند')),
            ],
            options={
                'verbose_name': 'مرحله فرآیند برنامه\u200cریزی',
                'verbose_name_plural': 'مراحل فرآیند برنامه\u200cریزی',
                'ordering': ['process', 'sort_order', 'step_number'],
                'unique_together': {('process', 'step_number')},
            },
        ),
    ]
