# Generated by Django 5.2.17 on 2026-09-10 08:04

import planning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_seed_planning_process_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyplanitem',
            name='uid',
            field=models.CharField(db_index=True, default=planning.models.generate_program_uid, editable=False, max_length=32, unique=True, verbose_name='شناسه برنامه'),
        ),
        migrations.AlterField(
            model_name='weeklyplanline',
            name='uid',
            field=models.CharField(blank=True, db_index=True, default='', help_text='شناسه ۱۴ رقمی مخصوص این نوع تولید', max_length=32, verbose_name='شناسه ردیف تولید'),
        ),
    ]
