# Generated by Django 5.2.17 on 2026-08-15 11:52

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فرم')),
                ('number', models.CharField(max_length=60, verbose_name='شماره فرم')),
                ('frames', models.JSONField(default=list, verbose_name='کادرها و چیدمان')),
                ('page_width_mm', models.PositiveIntegerField(default=210, verbose_name='عرض صفحه (مم)')),
                ('page_height_mm', models.PositiveIntegerField(default=297, verbose_name='ارتفاع صفحه (مم)')),
                ('is_standard', models.BooleanField(default=False, verbose_name='فرم استاندارد')),
                ('sent_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_print_forms', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_print_forms', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
                ('source_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_copies', to='reports.printform', verbose_name='فرم مبدأ')),
                ('viewers', models.ManyToManyField(blank=True, related_name='viewable_print_forms', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز به مشاهده')),
            ],
            options={
                'verbose_name': 'فرم چاپی',
                'verbose_name_plural': 'فرم\u200cهای چاپی',
                'ordering': ['-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'number'), name='uniq_form_number_per_owner')],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان گزارش')),
                ('number', models.CharField(max_length=60, verbose_name='شماره گزارش')),
                ('data_source', models.CharField(choices=[('fitting', 'تولید اتصالات'), ('pipe', 'تولید لوله'), ('product', 'اطلاعات کالا و موجودی')], default='fitting', max_length=20, verbose_name='منبع داده')),
                ('columns', models.JSONField(default=list, verbose_name='ستون\u200cها')),
                ('is_standard', models.BooleanField(default=False, verbose_name='گزارش استاندارد')),
                ('sent_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_reports', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_copies', to='reports.savedreport', verbose_name='گزارش مبدأ')),
                ('viewers', models.ManyToManyField(blank=True, related_name='viewable_reports', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز به مشاهده')),
            ],
            options={
                'verbose_name': 'گزارش ذخیره\u200cشده',
                'verbose_name_plural': 'گزارش\u200cهای ذخیره\u200cشده',
                'ordering': ['-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'number'), name='uniq_report_number_per_owner')],
            },
        ),
    ]
