# Generated by Django 5.2.17 on 2026-08-15 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printform',
            options={'ordering': ['number', 'id'], 'verbose_name': 'فرم چاپی', 'verbose_name_plural': 'فرم\u200cهای چاپی'},
        ),
        migrations.AlterModelOptions(
            name='savedreport',
            options={'ordering': ['number', 'id'], 'verbose_name': 'گزارش ذخیره\u200cشده', 'verbose_name_plural': 'گزارش\u200cهای ذخیره\u200cشده'},
        ),
        migrations.AddField(
            model_name='printform',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='printform',
            name='number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='شماره فرم'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='شماره گزارش'),
        ),
    ]
