# Generated by Django 5.2.17 on 2026-08-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_description_number_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='source_links',
            field=models.JSONField(blank=True, default=list, verbose_name='ربط منابع'),
        ),
    ]
