# Generated by Django 5.2.17 on 2026-08-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_source_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='printform',
            name='page_settings',
            field=models.JSONField(blank=True, default=dict, help_text='حاشیه چاپ، حساسیت اسنپ لبه و …', verbose_name='تنظیمات صفحه'),
        ),
    ]
