# Generated by Django 5.2.17 on 2026-08-17 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_printform_page_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='printform',
            name='linked_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_print_forms', to='reports.savedreport', verbose_name='گزارش مرتبط'),
        ),
        migrations.AddField(
            model_name='printform',
            name='purpose',
            field=models.CharField(blank=True, choices=[('weekly_planning', 'برنامه ریزی هفتگی'), ('production', 'برنامه های تولید'), ('reports', 'گزارش ها')], db_index=True, default='', max_length=40, verbose_name='کاربرد فرم'),
        ),
    ]
