# Generated by Django 5.2.17 on 2026-08-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_savedreport_access_mode_entry_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedreport',
            name='data_source',
            field=models.CharField(choices=[('fitting', 'تولید اتصالات'), ('pipe', 'تولید لوله'), ('product', 'اطلاعات کالا و موجودی'), ('data_entry', 'ثبت داده')], default='fitting', max_length=40, verbose_name='منبع داده'),
        ),
    ]
