# Generated by Django 5.2.17 on 2026-08-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_moldoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningInsightField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='عنوان نمایشی')),
                ('source', models.CharField(choices=[('product', 'اطلاعات کالا (کاتالوگ)'), ('last_production', 'آخرین تولید ذخیره\u200cشده'), ('file_column', 'ستون فایل / داده خارجی')], max_length=20, verbose_name='منبع داده')),
                ('source_key', models.CharField(help_text='برای کاتالوگ/تولید یکی از کلیدهای شناخته\u200cشده؛ برای فایل نام ستون.', max_length=80, verbose_name='کلید / ستون')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در صفحه')),
            ],
            options={
                'verbose_name': 'فیلد اطلاعات برنامه\u200cریزی',
                'verbose_name_plural': 'فیلدهای اطلاعات برنامه\u200cریزی (نوار شیشه\u200cای)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
