# Generated by Django 5.2.17 on 2026-08-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_planninginsightfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningDisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_coefficient', models.DecimalField(decimal_places=2, default=1, help_text='مثلاً ۱٫۲ یعنی ارتفاع کادر آبی ۲۰٪ بیشتر از حالت پایه.', max_digits=4, verbose_name='ضریب ارتفاع کادر آبی')),
                ('matrix_unit_numbers', models.CharField(default='1,2,4', help_text='شماره واحدها با ویرگول؛ مثلاً ۱,۲,۴', max_length=40, verbose_name='واحدهای جدول ماتریس')),
                ('show_group_breakdown', models.BooleanField(default=True, help_text='زیر هر واحد، تعداد قالب هر گروه محصول نمایش داده شود.', verbose_name='نمایش تفکیک گروه در کادر آبی')),
            ],
            options={
                'verbose_name': 'تنظیمات نمایش برنامه\u200cریزی',
                'verbose_name_plural': 'تنظیمات نمایش برنامه\u200cریزی (کادر آبی و ماتریس)',
            },
        ),
    ]
