# Generated by Django 5.2.17 on 2026-08-19 04:48

from django.db import migrations, models


def seed_default_scheme(apps, schema_editor):
    ProgramUidScheme = apps.get_model("catalog", "ProgramUidScheme")
    if ProgramUidScheme.objects.exists():
        return
    ProgramUidScheme.objects.create(
        name="قانون اصلی ۱۴ رقمی",
        is_active=True,
        base_year=1370,
        year_digits=2,
        program_digits=3,
        unit_digits=1,
        machine_digits=2,
        date_sum_digits=3,
        production_type_digits=1,
        mold_row_digits=2,
        segments_json=[
            {"key": "year", "digits": 2, "rule": "plan_year - base_year + 1", "label": "کد سال"},
            {"key": "program", "digits": 3, "rule": "program_number", "label": "شماره برنامه"},
            {"key": "unit", "digits": 1, "rule": "unit_number", "label": "واحد"},
            {"key": "machine", "digits": 2, "rule": "machine_number", "label": "دستگاه"},
            {
                "key": "date_sum",
                "digits": 3,
                "rule": "excel_offset(plan_date) + excel_offset(mold_change_date)",
                "label": "جمع روز برنامه و تعویض",
            },
            {
                "key": "production_type",
                "digits": 1,
                "rule": "1-based production type index on the item",
                "label": "نوع تولید",
            },
            {
                "key": "mold_row",
                "digits": 2,
                "rule": "1-based mold/row ordinal in the plan",
                "label": "ردیف قالب",
            },
        ],
        notes=(
            "YY=سال−۱۳۷۰+۱ | PPP=شماره برنامه | U=واحد | MM=دستگاه | "
            "DDD=جمع آفست اکسل تاریخ برنامه و تعویض قالب | T=نوع تولید | RR=ردیف قالب"
        ),
    )


def unseed(apps, schema_editor):
    ProgramUidScheme = apps.get_model("catalog", "ProgramUidScheme")
    ProgramUidScheme.objects.filter(name="قانون اصلی ۱۴ رقمی").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_planning_display_and_status_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramUidScheme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="قانون اصلی ۱۴ رقمی", max_length=120, verbose_name="نام قانون")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "base_year",
                    models.PositiveIntegerField(
                        default=1370,
                        help_text="کد سال = سال برنامه‌ریزی − مبدأ + ۱ (مثلاً ۱۴۰۵ با مبدأ ۱۳۷۰ → ۳۶).",
                        verbose_name="سال مبدأ شمسی",
                    ),
                ),
                ("year_digits", models.PositiveSmallIntegerField(default=2, verbose_name="ارقام کد سال")),
                ("program_digits", models.PositiveSmallIntegerField(default=3, verbose_name="ارقام شماره برنامه")),
                ("unit_digits", models.PositiveSmallIntegerField(default=1, verbose_name="ارقام واحد")),
                ("machine_digits", models.PositiveSmallIntegerField(default=2, verbose_name="ارقام دستگاه")),
                ("date_sum_digits", models.PositiveSmallIntegerField(default=3, verbose_name="ارقام جمع روزها")),
                ("production_type_digits", models.PositiveSmallIntegerField(default=1, verbose_name="ارقام نوع تولید")),
                ("mold_row_digits", models.PositiveSmallIntegerField(default=2, verbose_name="ارقام ردیف قالب")),
                (
                    "segments_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="ساختار قطعات برای مستندسازی و بازتعریف آینده.",
                        verbose_name="تعریف قطعات شناسه",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="شرح قانون برای اپراتور / برنامه‌نویس.",
                        verbose_name="توضیحات",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "قانون شناسه برنامه",
                "verbose_name_plural": "قانون شناسه برنامه (بازتعریف)",
            },
        ),
        migrations.RunPython(seed_default_scheme, unseed),
    ]
