# Generated by Django 5.2.17 on 2026-08-19 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_program_uid_scheme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('serious', 'جدی'), ('advisory', 'پیشنهادی')], db_index=True, default='serious', max_length=12, verbose_name='سطح')),
                ('kind', models.CharField(choices=[('uid_duplicate', 'تکرار شناسه برنامه'), ('other', 'سایر')], db_index=True, default='other', max_length=40, verbose_name='نوع')),
                ('status', models.CharField(choices=[('open', 'باز'), ('reviewed', 'بررسی\u200cشده'), ('cleared', 'پاک\u200cشده')], db_index=True, default='open', max_length=12, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='شرح')),
                ('suggestion', models.TextField(blank=True, help_text='برای آلارم\u200cهای جدی (مثل شناسه) راه\u200cحل پیشنهادی اینجا ثبت می\u200cشود.', verbose_name='پیشنهاد اصلاح')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
            ],
            options={
                'verbose_name': 'آلارم سیستم',
                'verbose_name_plural': 'آلارم\u200cهای سیستم (بررسی و پاک\u200cسازی)',
                'ordering': ['-created_at'],
            },
        ),
    ]
