# Generated by Django 5.2.17 on 2026-08-19 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_system_alarm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('file', models.FileField(help_text='فرمت\u200cهای رایج: .xlsx ، .xls ، .xlsm ، .csv', upload_to='excel_uploads/%Y/%m/', verbose_name='فایل اکسل')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='نام اصلی فایل')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بارگذارنده')),
            ],
            options={
                'verbose_name': 'فایل اکسل',
                'verbose_name_plural': 'فایل\u200cهای اکسل (سوابق آپلود)',
                'ordering': ['-created_at'],
            },
        ),
    ]
