# Generated by Django 5.2.17 on 2026-08-25 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_plan_date_unique_and_excel_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelupload',
            options={'ordering': ['-created_at'], 'verbose_name': 'فایل اکسل', 'verbose_name_plural': 'فایل\u200cهای اکسل'},
        ),
        migrations.AddField(
            model_name='excelupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='file',
            field=models.FileField(blank=True, help_text='فرمت\u200cهای رایج: .xlsx ، .xlsm ، .csv', null=True, upload_to='excel_uploads/%Y/%m/', verbose_name='فایل اکسل'),
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='title',
            field=models.CharField(max_length=200, verbose_name='نام فایل'),
        ),
        migrations.CreateModel(
            name='ExcelTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام جدول')),
                ('sheet_name', models.CharField(blank=True, max_length=200, verbose_name='نام شیت اصلی')),
                ('headers', models.JSONField(blank=True, default=list, verbose_name='ستون\u200cها')),
                ('rows', models.JSONField(blank=True, default=list, verbose_name='ردیف\u200cها')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='catalog.excelupload', verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'جدول اکسل',
                'verbose_name_plural': 'جداول اکسل',
                'ordering': ['order', 'id'],
            },
        ),
    ]
