# Generated by Django 5.2.17 on 2026-08-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_excel_tables_and_source_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceltable',
            name='layout',
            field=models.JSONField(blank=True, default=dict, help_text='عرض ستون\u200cها و ارتفاع ردیف\u200cها برای نمایش شبیه اکسل', verbose_name='چیدمان گرید'),
        ),
    ]
