# Generated by Django 5.2.17 on 2026-08-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_excel_table_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemalarm',
            name='kind',
            field=models.CharField(choices=[('uid_duplicate', 'تکرار شناسه برنامه'), ('data_transfer', 'انتقال داده اکسل'), ('other', 'سایر')], db_index=True, default='other', max_length=40, verbose_name='نوع'),
        ),
    ]
