# Generated by Django 5.2.17 on 2026-08-26 11:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_history_end_date_and_conflict_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_code', models.CharField(blank=True, max_length=40, verbose_name='کد جزء')),
                ('component_name', models.CharField(max_length=200, verbose_name='نام جزء')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=14, verbose_name='مقدار')),
                ('unit', models.CharField(blank=True, default='عدد', max_length=40, verbose_name='واحد')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='catalog.product', verbose_name='محصول والد')),
            ],
            options={
                'verbose_name': 'سطر BOM',
                'verbose_name_plural': 'ساختار BOM',
                'ordering': ['parent__code', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(blank=True, max_length=40, verbose_name='کد ماده')),
                ('material_name', models.CharField(max_length=200, verbose_name='نام ماده')),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='مقدار به ازای واحد محصول')),
                ('unit', models.CharField(blank=True, default='گرم', max_length=40, verbose_name='واحد')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ماده مصرفی',
                'verbose_name_plural': 'مواد مصرفی',
                'ordering': ['product__code', 'order', 'id'],
            },
        ),
    ]
