# Generated by Django 5.2.17 on 2026-09-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_bom_and_consumables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningdisplaysettings',
            name='height_coefficient',
            field=models.DecimalField(decimal_places=2, default=1, help_text='مثلاً ۱٫۲ یعنی عرض کادر آبی ۲۰٪ بیشتر از حالت پایه.', max_digits=4, verbose_name='ضریب عرض کادر آبی'),
        ),
    ]
