# Generated by Django 5.2.17 on 2026-09-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_planning_display_width_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNamingKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='شناسه ثابت برنامه\u200cنویسی؛ با تغییر عنوان عوض نمی\u200cشود.', max_length=220, unique=True, verbose_name='کلید پایدار')),
                ('label', models.CharField(max_length=200, verbose_name='عنوان نمایشی')),
                ('default_label', models.CharField(blank=True, max_length=200, verbose_name='عنوان پیش\u200cفرض')),
                ('address', models.CharField(blank=True, db_index=True, help_text='مسیر پیدا کردن در سامانه / کد، مثلاً templates/...#data-col=…', max_length=400, verbose_name='آدرس دقیق')),
                ('category', models.CharField(choices=[('section', 'بخش سیستم'), ('table', 'جدول / صفحه'), ('column', 'سرستون'), ('transfer', 'انتقال داده'), ('report', 'گزارش'), ('status', 'وضعیت'), ('uid', 'شناسه / UID'), ('other', 'سایر')], db_index=True, default='other', max_length=20, verbose_name='دسته')),
                ('section_key', models.CharField(blank=True, db_index=True, help_text='ارجاع به آیتم داده\u200cهای سیستم (مثلاً weekly_plans)', max_length=80, verbose_name='کلید بخش سیستم')),
                ('linked_section_key', models.CharField(blank=True, db_index=True, help_text='اختیاری: لینک معنایی به بخش دیگری از سامانه', max_length=80, verbose_name='ربط به بخش دیگر')),
                ('table_key', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='کلید جدول')),
                ('column_key', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='کلید ستون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, help_text='غیرفعال = پنهان\u200cکردن سرستون از UIهایی که رجیستری را می\u200cخوانند', verbose_name='فعال / نمایش')),
                ('is_custom', models.BooleanField(default=False, help_text='ستون/کلید دستی که در بذر اولیه نبوده است', verbose_name='افزوده توسط کاربر')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کلید نام\u200cگذاری سیستم',
                'verbose_name_plural': 'کلیدهای نام\u200cگذاری سیستم',
                'ordering': ['category', 'table_key', 'order', 'key'],
                'indexes': [models.Index(fields=['table_key', 'order'], name='catalog_sys_table_k_8558bf_idx'), models.Index(fields=['category', 'is_active'], name='catalog_sys_categor_d0f570_idx')],
            },
        ),
    ]
