# Generated by Django 5.2.17 on 2026-09-03 16:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_deactivate_obsolete_transfer_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipeProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='کد خط')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('layer_mode', models.CharField(choices=[('single', 'تک\u200cلایه'), ('triple', 'سه\u200cلایه'), ('custom', 'سفارشی / بعداً')], default='single', max_length=20, verbose_name='حالت لایه')),
                ('needs_billing', models.BooleanField(default=False, verbose_name='نیاز به بلینگ (سوکت\u200cزنی)')),
                ('uses_nominal_lengths', models.BooleanField(default=False, verbose_name='طول\u200cهای اسمی مشترک (یک\u200cسر/دوسر سوکت)')),
                ('is_scaffold', models.BooleanField(default=False, help_text='خط\u200cهایی که فقط اسکلت دارند تا تنظیمات کامل شود.', verbose_name='داربست (جزئیات بعداً)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات ویژه')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'خط محصول لوله',
                'verbose_name_plural': 'خطوط محصول لوله',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PipeSizeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_mm', models.PositiveIntegerField(verbose_name='سایز (mm)')),
                ('line_speed_m_per_min', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='سرعت خط (m/min)')),
                ('billing_pieces_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='برای دوسر سوکت زمان بلینگ تقریباً دوبرابر می\u200cشود.', max_digits=10, verbose_name='ظرفیت بلینگ (عدد/ساعت برای هر سر سوکت)')),
                ('pack_qty', models.PositiveIntegerField(default=0, verbose_name='تعداد در بسته')),
                ('depot_ceiling', models.PositiveIntegerField(default=0, verbose_name='سقف دپو (عدد)')),
                ('stock_on_hand', models.IntegerField(default=0, help_text='اسنپ\u200cشات سبک؛ می\u200cتواند از کاتالوگ/حواله همگام شود.', verbose_name='موجودی فعلی (عدد)')),
                ('material_note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت مواد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('extras', models.JSONField(blank=True, default=dict, verbose_name='پارامترهای اضافی')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalog.pipeproductline', verbose_name='خط')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipe_size_profiles', to='catalog.product', verbose_name='محصول کاتالوگ (اختیاری)')),
            ],
            options={
                'verbose_name': 'پروفایل سایز لوله',
                'verbose_name_plural': 'پروفایل\u200cهای سایز لوله',
                'ordering': ['line__order', 'size_mm'],
                'unique_together': {('line', 'size_mm')},
            },
        ),
        migrations.CreateModel(
            name='PipeLengthCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_code', models.CharField(max_length=20, verbose_name='کد طول')),
                ('label', models.CharField(max_length=80, verbose_name='نام طول')),
                ('nominal_cm', models.PositiveIntegerField(verbose_name='طول اسمی (cm)')),
                ('cut_length_mm', models.PositiveIntegerField(verbose_name='طول برش واقعی (mm)')),
                ('socket_ends', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد سر سوکت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('size_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='length_cuts', to='catalog.pipesizeprofile', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'طول برش لوله',
                'verbose_name_plural': 'طول\u200cهای برش لوله',
                'ordering': ['size_profile', 'nominal_cm', 'socket_ends'],
                'unique_together': {('size_profile', 'length_code')},
            },
        ),
        migrations.CreateModel(
            name='PipeLayerSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(default='single', max_length=20, verbose_name='لایه')),
                ('material_code', models.CharField(blank=True, max_length=40, verbose_name='کد ماده')),
                ('material_name', models.CharField(blank=True, max_length=120, verbose_name='نام ماده')),
                ('kg_per_meter', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=12, verbose_name='kg در متر')),
                ('share_percent', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='برای سه\u200cلایه جمع سهم\u200cها باید حدود ۱۰۰ باشد.', max_digits=6, verbose_name='سهم درصد')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('size_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='catalog.pipesizeprofile', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'لایه مواد لوله',
                'verbose_name_plural': 'لایه\u200cهای مواد لوله',
                'ordering': ['size_profile', 'order', 'id'],
                'unique_together': {('size_profile', 'layer')},
            },
        ),
    ]
