# Generated by Django 5.2.17 on 2026-09-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_pipe_calc_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableLayoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_height_px', models.PositiveSmallIntegerField(default=36, help_text='بین ۱۸ تا ۱۲۰. روی همه جداول سامانه اعمال می\u200cشود.', verbose_name='ارتفاع یکنواخت ردیف جداول (پیکسل)')),
                ('section_width_locks', models.JSONField(blank=True, default=dict, help_text='مثال: {"reports": true, "history": false}', verbose_name='قفل عرض ستون به تفکیک بخش')),
            ],
            options={
                'verbose_name': 'تنظیمات نمایش جداول',
                'verbose_name_plural': 'تنظیمات نمایش جداول (ارتفاع ردیف و قفل عرض)',
            },
        ),
    ]
