# Generated by Django 5.2.17 on 2026-09-03 22:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_table_layout_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelengthcut',
            name='avg_monthly_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='میانگین فروش ماهانه'),
        ),
        migrations.AddField(
            model_name='pipelengthcut',
            name='depot_ceiling',
            field=models.PositiveIntegerField(default=0, help_text='سقف دپوی این طول اسمی؛ برای همه محصولات قابل تعریف است.', verbose_name='سقف دپو (عدد)'),
        ),
        migrations.AddField(
            model_name='pipelengthcut',
            name='stock_on_hand',
            field=models.IntegerField(default=0, help_text='از داده محصولات همگام می\u200cشود؛ در صورت نیاز قابل ویرایش است.', verbose_name='موجودی (عدد)'),
        ),
        migrations.AddField(
            model_name='pipelengthcut',
            name='voucher_qty',
            field=models.IntegerField(default=0, help_text='از تب حواله\u200cهای داده محصولات خوانده می\u200cشود.', verbose_name='حواله (عدد)'),
        ),
        migrations.CreateModel(
            name='PipeCalcRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, verbose_name='کد قانون')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('socket_cap_per_socket', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10, verbose_name='درپوش سوکت به ازای هر سر')),
                ('pipe_cap_per_piece', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10, verbose_name='درپوش لوله به ازای هر شاخه')),
                ('spacer_per_piece', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='اسپیسر به ازای هر شاخه')),
                ('cover_per_piece', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='کاور به ازای هر شاخه')),
                ('material_factors', models.JSONField(blank=True, default=dict, verbose_name='ضرایب ترکیب مواد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('line', models.ForeignKey(blank=True, help_text='خالی = قانون سراسری برای همه خطوط ماتریسی.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_rules', to='catalog.pipeproductline', verbose_name='خط')),
            ],
            options={
                'verbose_name': 'قانون محاسبه زمان تولید',
                'verbose_name_plural': 'قوانین محاسبه زمان تولید',
                'ordering': ['line__order', 'code'],
                'unique_together': {('line', 'code')},
            },
        ),
    ]
