# Generated by Django 5.2.17 on 2026-09-17 10:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_reactivate_planning_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelengthcut',
            name='cover_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='طول کاور (cm)'),
        ),
        migrations.AddField(
            model_name='pipelengthcut',
            name='pack_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد در بسته'),
        ),
        migrations.AddField(
            model_name='pipelengthcut',
            name='pipe_cap_per_piece',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='درپوش لوله برای هر شاخه'),
        ),
        migrations.AddField(
            model_name='pipelengthcut',
            name='sku_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='کد کالا'),
        ),
        migrations.AddField(
            model_name='pipelengthcut',
            name='spacers_per_pack',
            field=models.PositiveIntegerField(default=0, verbose_name='اسپیسر در هر بسته'),
        ),
        migrations.AddField(
            model_name='pipesizeprofile',
            name='billing_cavities',
            field=models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=6, verbose_name='حفره بلینگ'),
        ),
        migrations.AddField(
            model_name='pipesizeprofile',
            name='billing_cycle_seconds',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='سیکل بلینگ (ثانیه)'),
        ),
        migrations.AddField(
            model_name='pipesizeprofile',
            name='cover_g_per_m',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='وزن یک متر کاور (گرم)'),
        ),
        migrations.AddField(
            model_name='pipesizeprofile',
            name='kg_per_meter',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=12, verbose_name='وزن یک متر لوله (kg)'),
        ),
        migrations.AddField(
            model_name='pipesizeprofile',
            name='oring_bag_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='اورینگ در کیسه'),
        ),
        migrations.AddField(
            model_name='pipesizeprofile',
            name='pipe_cap_bag_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='درپوش لوله در کیسه'),
        ),
        migrations.AddField(
            model_name='pipesizeprofile',
            name='socket_cap_bag_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='درپوش سوکت در کیسه'),
        ),
        migrations.AddField(
            model_name='pipesizeprofile',
            name='spacer_bag_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='اسپیسر در کیسه'),
        ),
        migrations.AlterField(
            model_name='pipesizeprofile',
            name='billing_pieces_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='قدیمی؛ اگر سیکل و حفره پر باشد استفاده نمی\u200cشود.', max_digits=10, verbose_name='ظرفیت بلینگ (عدد/ساعت برای هر سر سوکت)'),
        ),
    ]
