# Generated by Django 5.2.17 on 2026-09-13 12:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_reactivate_planning_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(default=1, verbose_name='اولویت قالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'قالب مجاز محصول',
                'verbose_name_plural': 'قالب\u200cهای مجاز محصول',
                'ordering': ['product__code', 'slot', 'id'],
            },
        ),
        migrations.AddField(
            model_name='moldoption',
            name='change_time_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, verbose_name='زمان تعویض قالب (ساعت)'),
        ),
        migrations.AddField(
            model_name='moldoption',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='کد قالب'),
        ),
        migrations.AddField(
            model_name='moldoption',
            name='copies',
            field=models.PositiveSmallIntegerField(default=1, help_text='هر نسخه همزمان فقط روی یک دستگاه اجرا می\u200cشود.', verbose_name='تعداد نسخهٔ فیزیکی'),
        ),
        migrations.AlterField(
            model_name='moldoption',
            name='label',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AddConstraint(
            model_name='moldoption',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('code',), name='uniq_moldoption_code'),
        ),
        migrations.AddField(
            model_name='productmold',
            name='mold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='catalog.moldoption', verbose_name='قالب'),
        ),
        migrations.AddField(
            model_name='productmold',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mold_links', to='catalog.product', verbose_name='محصول'),
        ),
        migrations.AlterUniqueTogether(
            name='productmold',
            unique_together={('product', 'mold')},
        ),
    ]
