@echo off
REM ============================================================
REM  ساخت فایل .env برای اتصال به PostgreSQL
REM  Creates the project-root .env with the database credentials.
REM  Fixes the PostgreSQL error: "fe_sendauth: no password supplied"
REM  by making sure DB_PASSWORD (and the other DB_* values) are set.
REM ============================================================
setlocal
cd /d "%~dp0.."
set "ENV_FILE=%CD%\.env"

echo(
echo ============================================================
echo   Database (.env) setup  -^>  "%ENV_FILE%"
echo ============================================================
echo(

if not exist "%ENV_FILE%" goto collect
set "OVERWRITE=N"
set /p "OVERWRITE=A .env already exists. Overwrite it? (y/N): "
if /I "%OVERWRITE%"=="y" goto collect
echo Keeping the existing .env. Nothing changed.
goto done

:collect
set /p "IN_NAME=DB_NAME [erp_db]: "
if not defined IN_NAME set "IN_NAME=erp_db"

set /p "IN_USER=DB_USER [erp_user]: "
if not defined IN_USER set "IN_USER=erp_user"

:ask_pass
set "IN_PASS="
set /p "IN_PASS=DB_PASSWORD (required, must match the erp_user role): "
if defined IN_PASS goto have_pass
echo Password cannot be empty. Please try again.
goto ask_pass
:have_pass

set /p "IN_HOST=DB_HOST [127.0.0.1]: "
if not defined IN_HOST set "IN_HOST=127.0.0.1"

set /p "IN_PORT=DB_PORT [5432]: "
if not defined IN_PORT set "IN_PORT=5432"

REM --- Write the .env file (project root) ---
> "%ENV_FILE%" echo # Generated by scripts\setup_env.bat  --  do NOT commit real secrets.
>>"%ENV_FILE%" echo DB_ENGINE=postgresql
>>"%ENV_FILE%" echo DB_NAME=%IN_NAME%
>>"%ENV_FILE%" echo DB_USER=%IN_USER%
>>"%ENV_FILE%" echo DB_PASSWORD=%IN_PASS%
>>"%ENV_FILE%" echo DB_HOST=%IN_HOST%
>>"%ENV_FILE%" echo DB_PORT=%IN_PORT%
>>"%ENV_FILE%" echo DB_CONNECT_TIMEOUT=5
echo Wrote "%ENV_FILE%".
echo(

REM --- Optional: quick connection test when the virtualenv exists ---
if not exist ".venv\Scripts\python.exe" goto steps
echo Testing the database connection ...
set "DB_ENGINE=postgresql"
set "DB_NAME=%IN_NAME%"
set "DB_USER=%IN_USER%"
set "DB_PASSWORD=%IN_PASS%"
set "DB_HOST=%IN_HOST%"
set "DB_PORT=%IN_PORT%"
".venv\Scripts\python.exe" -c "import os,psycopg;psycopg.connect(host=os.environ['DB_HOST'],port=os.environ['DB_PORT'],dbname=os.environ['DB_NAME'],user=os.environ['DB_USER'],password=os.environ['DB_PASSWORD'],connect_timeout=5).close();print('[OK] Database connection succeeded.')" 2>nul
if not errorlevel 1 goto steps
echo [FAIL] Could not connect. Most likely the password does not match the
echo        "%IN_USER%" role, or the database "%IN_NAME%" does not exist yet.
echo        In psql (as the postgres superuser) you can fix it with:
echo            ALTER ROLE %IN_USER% WITH PASSWORD '%IN_PASS%';
echo            CREATE DATABASE %IN_NAME% OWNER %IN_USER%;

:steps
echo(
echo Next steps:
echo    scripts\windows_setup.bat
echo    scripts\windows_run.bat

:done
echo(
pause
endlocal
